#include "common.h"
#include <include/gpu/vk/VulkanBackendContext.h>
#include <include/gpu/ganesh/vk/GrVkTypes.h>

void initGrContext_vk(py::module &m) {

py::enum_<VkFormat>(m, "VkFormat")
    .value("UNDEFINED",                                      VkFormat::VK_FORMAT_UNDEFINED)
    .value("R4G4_UNORM_PACK8",                               VkFormat::VK_FORMAT_R4G4_UNORM_PACK8)
    .value("R4G4B4A4_UNORM_PACK16",                          VkFormat::VK_FORMAT_R4G4B4A4_UNORM_PACK16)
    .value("B4G4R4A4_UNORM_PACK16",                          VkFormat::VK_FORMAT_B4G4R4A4_UNORM_PACK16)
    .value("R5G6B5_UNORM_PACK16",                            VkFormat::VK_FORMAT_R5G6B5_UNORM_PACK16)
    .value("B5G6R5_UNORM_PACK16",                            VkFormat::VK_FORMAT_B5G6R5_UNORM_PACK16)
    .value("R5G5B5A1_UNORM_PACK16",                          VkFormat::VK_FORMAT_R5G5B5A1_UNORM_PACK16)
    .value("B5G5R5A1_UNORM_PACK16",                          VkFormat::VK_FORMAT_B5G5R5A1_UNORM_PACK16)
    .value("A1R5G5B5_UNORM_PACK16",                          VkFormat::VK_FORMAT_A1R5G5B5_UNORM_PACK16)
    .value("R8_UNORM",                                       VkFormat::VK_FORMAT_R8_UNORM)
    .value("R8_SNORM",                                       VkFormat::VK_FORMAT_R8_SNORM)
    .value("R8_USCALED",                                     VkFormat::VK_FORMAT_R8_USCALED)
    .value("R8_SSCALED",                                     VkFormat::VK_FORMAT_R8_SSCALED)
    .value("R8_UINT",                                        VkFormat::VK_FORMAT_R8_UINT)
    .value("R8_SINT",                                        VkFormat::VK_FORMAT_R8_SINT)
    .value("R8_SRGB",                                        VkFormat::VK_FORMAT_R8_SRGB)
    .value("R8G8_UNORM",                                     VkFormat::VK_FORMAT_R8G8_UNORM)
    .value("R8G8_SNORM",                                     VkFormat::VK_FORMAT_R8G8_SNORM)
    .value("R8G8_USCALED",                                   VkFormat::VK_FORMAT_R8G8_USCALED)
    .value("R8G8_SSCALED",                                   VkFormat::VK_FORMAT_R8G8_SSCALED)
    .value("R8G8_UINT",                                      VkFormat::VK_FORMAT_R8G8_UINT)
    .value("R8G8_SINT",                                      VkFormat::VK_FORMAT_R8G8_SINT)
    .value("R8G8_SRGB",                                      VkFormat::VK_FORMAT_R8G8_SRGB)
    .value("R8G8B8_UNORM",                                   VkFormat::VK_FORMAT_R8G8B8_UNORM)
    .value("R8G8B8_SNORM",                                   VkFormat::VK_FORMAT_R8G8B8_SNORM)
    .value("R8G8B8_USCALED",                                 VkFormat::VK_FORMAT_R8G8B8_USCALED)
    .value("R8G8B8_SSCALED",                                 VkFormat::VK_FORMAT_R8G8B8_SSCALED)
    .value("R8G8B8_UINT",                                    VkFormat::VK_FORMAT_R8G8B8_UINT)
    .value("R8G8B8_SINT",                                    VkFormat::VK_FORMAT_R8G8B8_SINT)
    .value("R8G8B8_SRGB",                                    VkFormat::VK_FORMAT_R8G8B8_SRGB)
    .value("B8G8R8_UNORM",                                   VkFormat::VK_FORMAT_B8G8R8_UNORM)
    .value("B8G8R8_SNORM",                                   VkFormat::VK_FORMAT_B8G8R8_SNORM)
    .value("B8G8R8_USCALED",                                 VkFormat::VK_FORMAT_B8G8R8_USCALED)
    .value("B8G8R8_SSCALED",                                 VkFormat::VK_FORMAT_B8G8R8_SSCALED)
    .value("B8G8R8_UINT",                                    VkFormat::VK_FORMAT_B8G8R8_UINT)
    .value("B8G8R8_SINT",                                    VkFormat::VK_FORMAT_B8G8R8_SINT)
    .value("B8G8R8_SRGB",                                    VkFormat::VK_FORMAT_B8G8R8_SRGB)
    .value("R8G8B8A8_UNORM",                                 VkFormat::VK_FORMAT_R8G8B8A8_UNORM)
    .value("R8G8B8A8_SNORM",                                 VkFormat::VK_FORMAT_R8G8B8A8_SNORM)
    .value("R8G8B8A8_USCALED",                               VkFormat::VK_FORMAT_R8G8B8A8_USCALED)
    .value("R8G8B8A8_SSCALED",                               VkFormat::VK_FORMAT_R8G8B8A8_SSCALED)
    .value("R8G8B8A8_UINT",                                  VkFormat::VK_FORMAT_R8G8B8A8_UINT)
    .value("R8G8B8A8_SINT",                                  VkFormat::VK_FORMAT_R8G8B8A8_SINT)
    .value("R8G8B8A8_SRGB",                                  VkFormat::VK_FORMAT_R8G8B8A8_SRGB)
    .value("B8G8R8A8_UNORM",                                 VkFormat::VK_FORMAT_B8G8R8A8_UNORM)
    .value("B8G8R8A8_SNORM",                                 VkFormat::VK_FORMAT_B8G8R8A8_SNORM)
    .value("B8G8R8A8_USCALED",                               VkFormat::VK_FORMAT_B8G8R8A8_USCALED)
    .value("B8G8R8A8_SSCALED",                               VkFormat::VK_FORMAT_B8G8R8A8_SSCALED)
    .value("B8G8R8A8_UINT",                                  VkFormat::VK_FORMAT_B8G8R8A8_UINT)
    .value("B8G8R8A8_SINT",                                  VkFormat::VK_FORMAT_B8G8R8A8_SINT)
    .value("B8G8R8A8_SRGB",                                  VkFormat::VK_FORMAT_B8G8R8A8_SRGB)
    .value("A8B8G8R8_UNORM_PACK32",                          VkFormat::VK_FORMAT_A8B8G8R8_UNORM_PACK32)
    .value("A8B8G8R8_SNORM_PACK32",                          VkFormat::VK_FORMAT_A8B8G8R8_SNORM_PACK32)
    .value("A8B8G8R8_USCALED_PACK32",                        VkFormat::VK_FORMAT_A8B8G8R8_USCALED_PACK32)
    .value("A8B8G8R8_SSCALED_PACK32",                        VkFormat::VK_FORMAT_A8B8G8R8_SSCALED_PACK32)
    .value("A8B8G8R8_UINT_PACK32",                           VkFormat::VK_FORMAT_A8B8G8R8_UINT_PACK32)
    .value("A8B8G8R8_SINT_PACK32",                           VkFormat::VK_FORMAT_A8B8G8R8_SINT_PACK32)
    .value("A8B8G8R8_SRGB_PACK32",                           VkFormat::VK_FORMAT_A8B8G8R8_SRGB_PACK32)
    .value("A2R10G10B10_UNORM_PACK32",                       VkFormat::VK_FORMAT_A2R10G10B10_UNORM_PACK32)
    .value("A2R10G10B10_SNORM_PACK32",                       VkFormat::VK_FORMAT_A2R10G10B10_SNORM_PACK32)
    .value("A2R10G10B10_USCALED_PACK32",                     VkFormat::VK_FORMAT_A2R10G10B10_USCALED_PACK32)
    .value("A2R10G10B10_SSCALED_PACK32",                     VkFormat::VK_FORMAT_A2R10G10B10_SSCALED_PACK32)
    .value("A2R10G10B10_UINT_PACK32",                        VkFormat::VK_FORMAT_A2R10G10B10_UINT_PACK32)
    .value("A2R10G10B10_SINT_PACK32",                        VkFormat::VK_FORMAT_A2R10G10B10_SINT_PACK32)
    .value("A2B10G10R10_UNORM_PACK32",                       VkFormat::VK_FORMAT_A2B10G10R10_UNORM_PACK32)
    .value("A2B10G10R10_SNORM_PACK32",                       VkFormat::VK_FORMAT_A2B10G10R10_SNORM_PACK32)
    .value("A2B10G10R10_USCALED_PACK32",                     VkFormat::VK_FORMAT_A2B10G10R10_USCALED_PACK32)
    .value("A2B10G10R10_SSCALED_PACK32",                     VkFormat::VK_FORMAT_A2B10G10R10_SSCALED_PACK32)
    .value("A2B10G10R10_UINT_PACK32",                        VkFormat::VK_FORMAT_A2B10G10R10_UINT_PACK32)
    .value("A2B10G10R10_SINT_PACK32",                        VkFormat::VK_FORMAT_A2B10G10R10_SINT_PACK32)
    .value("R16_UNORM",                                      VkFormat::VK_FORMAT_R16_UNORM)
    .value("R16_SNORM",                                      VkFormat::VK_FORMAT_R16_SNORM)
    .value("R16_USCALED",                                    VkFormat::VK_FORMAT_R16_USCALED)
    .value("R16_SSCALED",                                    VkFormat::VK_FORMAT_R16_SSCALED)
    .value("R16_UINT",                                       VkFormat::VK_FORMAT_R16_UINT)
    .value("R16_SINT",                                       VkFormat::VK_FORMAT_R16_SINT)
    .value("R16_SFLOAT",                                     VkFormat::VK_FORMAT_R16_SFLOAT)
    .value("R16G16_UNORM",                                   VkFormat::VK_FORMAT_R16G16_UNORM)
    .value("R16G16_SNORM",                                   VkFormat::VK_FORMAT_R16G16_SNORM)
    .value("R16G16_USCALED",                                 VkFormat::VK_FORMAT_R16G16_USCALED)
    .value("R16G16_SSCALED",                                 VkFormat::VK_FORMAT_R16G16_SSCALED)
    .value("R16G16_UINT",                                    VkFormat::VK_FORMAT_R16G16_UINT)
    .value("R16G16_SINT",                                    VkFormat::VK_FORMAT_R16G16_SINT)
    .value("R16G16_SFLOAT",                                  VkFormat::VK_FORMAT_R16G16_SFLOAT)
    .value("R16G16B16_UNORM",                                VkFormat::VK_FORMAT_R16G16B16_UNORM)
    .value("R16G16B16_SNORM",                                VkFormat::VK_FORMAT_R16G16B16_SNORM)
    .value("R16G16B16_USCALED",                              VkFormat::VK_FORMAT_R16G16B16_USCALED)
    .value("R16G16B16_SSCALED",                              VkFormat::VK_FORMAT_R16G16B16_SSCALED)
    .value("R16G16B16_UINT",                                 VkFormat::VK_FORMAT_R16G16B16_UINT)
    .value("R16G16B16_SINT",                                 VkFormat::VK_FORMAT_R16G16B16_SINT)
    .value("R16G16B16_SFLOAT",                               VkFormat::VK_FORMAT_R16G16B16_SFLOAT)
    .value("R16G16B16A16_UNORM",                             VkFormat::VK_FORMAT_R16G16B16A16_UNORM)
    .value("R16G16B16A16_SNORM",                             VkFormat::VK_FORMAT_R16G16B16A16_SNORM)
    .value("R16G16B16A16_USCALED",                           VkFormat::VK_FORMAT_R16G16B16A16_USCALED)
    .value("R16G16B16A16_SSCALED",                           VkFormat::VK_FORMAT_R16G16B16A16_SSCALED)
    .value("R16G16B16A16_UINT",                              VkFormat::VK_FORMAT_R16G16B16A16_UINT)
    .value("R16G16B16A16_SINT",                              VkFormat::VK_FORMAT_R16G16B16A16_SINT)
    .value("R16G16B16A16_SFLOAT",                            VkFormat::VK_FORMAT_R16G16B16A16_SFLOAT)
    .value("R32_UINT",                                       VkFormat::VK_FORMAT_R32_UINT)
    .value("R32_SINT",                                       VkFormat::VK_FORMAT_R32_SINT)
    .value("R32_SFLOAT",                                     VkFormat::VK_FORMAT_R32_SFLOAT)
    .value("R32G32_UINT",                                    VkFormat::VK_FORMAT_R32G32_UINT)
    .value("R32G32_SINT",                                    VkFormat::VK_FORMAT_R32G32_SINT)
    .value("R32G32_SFLOAT",                                  VkFormat::VK_FORMAT_R32G32_SFLOAT)
    .value("R32G32B32_UINT",                                 VkFormat::VK_FORMAT_R32G32B32_UINT)
    .value("R32G32B32_SINT",                                 VkFormat::VK_FORMAT_R32G32B32_SINT)
    .value("R32G32B32_SFLOAT",                               VkFormat::VK_FORMAT_R32G32B32_SFLOAT)
    .value("R32G32B32A32_UINT",                              VkFormat::VK_FORMAT_R32G32B32A32_UINT)
    .value("R32G32B32A32_SINT",                              VkFormat::VK_FORMAT_R32G32B32A32_SINT)
    .value("R32G32B32A32_SFLOAT",                            VkFormat::VK_FORMAT_R32G32B32A32_SFLOAT)
    .value("R64_UINT",                                       VkFormat::VK_FORMAT_R64_UINT)
    .value("R64_SINT",                                       VkFormat::VK_FORMAT_R64_SINT)
    .value("R64_SFLOAT",                                     VkFormat::VK_FORMAT_R64_SFLOAT)
    .value("R64G64_UINT",                                    VkFormat::VK_FORMAT_R64G64_UINT)
    .value("R64G64_SINT",                                    VkFormat::VK_FORMAT_R64G64_SINT)
    .value("R64G64_SFLOAT",                                  VkFormat::VK_FORMAT_R64G64_SFLOAT)
    .value("R64G64B64_UINT",                                 VkFormat::VK_FORMAT_R64G64B64_UINT)
    .value("R64G64B64_SINT",                                 VkFormat::VK_FORMAT_R64G64B64_SINT)
    .value("R64G64B64_SFLOAT",                               VkFormat::VK_FORMAT_R64G64B64_SFLOAT)
    .value("R64G64B64A64_UINT",                              VkFormat::VK_FORMAT_R64G64B64A64_UINT)
    .value("R64G64B64A64_SINT",                              VkFormat::VK_FORMAT_R64G64B64A64_SINT)
    .value("R64G64B64A64_SFLOAT",                            VkFormat::VK_FORMAT_R64G64B64A64_SFLOAT)
    .value("B10G11R11_UFLOAT_PACK32",                        VkFormat::VK_FORMAT_B10G11R11_UFLOAT_PACK32)
    .value("E5B9G9R9_UFLOAT_PACK32",                         VkFormat::VK_FORMAT_E5B9G9R9_UFLOAT_PACK32)
    .value("D16_UNORM",                                      VkFormat::VK_FORMAT_D16_UNORM)
    .value("X8_D24_UNORM_PACK32",                            VkFormat::VK_FORMAT_X8_D24_UNORM_PACK32)
    .value("D32_SFLOAT",                                     VkFormat::VK_FORMAT_D32_SFLOAT)
    .value("S8_UINT",                                        VkFormat::VK_FORMAT_S8_UINT)
    .value("D16_UNORM_S8_UINT",                              VkFormat::VK_FORMAT_D16_UNORM_S8_UINT)
    .value("D24_UNORM_S8_UINT",                              VkFormat::VK_FORMAT_D24_UNORM_S8_UINT)
    .value("D32_SFLOAT_S8_UINT",                             VkFormat::VK_FORMAT_D32_SFLOAT_S8_UINT)
    .value("BC1_RGB_UNORM_BLOCK",                            VkFormat::VK_FORMAT_BC1_RGB_UNORM_BLOCK)
    .value("BC1_RGB_SRGB_BLOCK",                             VkFormat::VK_FORMAT_BC1_RGB_SRGB_BLOCK)
    .value("BC1_RGBA_UNORM_BLOCK",                           VkFormat::VK_FORMAT_BC1_RGBA_UNORM_BLOCK)
    .value("BC1_RGBA_SRGB_BLOCK",                            VkFormat::VK_FORMAT_BC1_RGBA_SRGB_BLOCK)
    .value("BC2_UNORM_BLOCK",                                VkFormat::VK_FORMAT_BC2_UNORM_BLOCK)
    .value("BC2_SRGB_BLOCK",                                 VkFormat::VK_FORMAT_BC2_SRGB_BLOCK)
    .value("BC3_UNORM_BLOCK",                                VkFormat::VK_FORMAT_BC3_UNORM_BLOCK)
    .value("BC3_SRGB_BLOCK",                                 VkFormat::VK_FORMAT_BC3_SRGB_BLOCK)
    .value("BC4_UNORM_BLOCK",                                VkFormat::VK_FORMAT_BC4_UNORM_BLOCK)
    .value("BC4_SNORM_BLOCK",                                VkFormat::VK_FORMAT_BC4_SNORM_BLOCK)
    .value("BC5_UNORM_BLOCK",                                VkFormat::VK_FORMAT_BC5_UNORM_BLOCK)
    .value("BC5_SNORM_BLOCK",                                VkFormat::VK_FORMAT_BC5_SNORM_BLOCK)
    .value("BC6H_UFLOAT_BLOCK",                              VkFormat::VK_FORMAT_BC6H_UFLOAT_BLOCK)
    .value("BC6H_SFLOAT_BLOCK",                              VkFormat::VK_FORMAT_BC6H_SFLOAT_BLOCK)
    .value("BC7_UNORM_BLOCK",                                VkFormat::VK_FORMAT_BC7_UNORM_BLOCK)
    .value("BC7_SRGB_BLOCK",                                 VkFormat::VK_FORMAT_BC7_SRGB_BLOCK)
    .value("ETC2_R8G8B8_UNORM_BLOCK",                        VkFormat::VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK)
    .value("ETC2_R8G8B8_SRGB_BLOCK",                         VkFormat::VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK)
    .value("ETC2_R8G8B8A1_UNORM_BLOCK",                      VkFormat::VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK)
    .value("ETC2_R8G8B8A1_SRGB_BLOCK",                       VkFormat::VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK)
    .value("ETC2_R8G8B8A8_UNORM_BLOCK",                      VkFormat::VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK)
    .value("ETC2_R8G8B8A8_SRGB_BLOCK",                       VkFormat::VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK)
    .value("EAC_R11_UNORM_BLOCK",                            VkFormat::VK_FORMAT_EAC_R11_UNORM_BLOCK)
    .value("EAC_R11_SNORM_BLOCK",                            VkFormat::VK_FORMAT_EAC_R11_SNORM_BLOCK)
    .value("EAC_R11G11_UNORM_BLOCK",                         VkFormat::VK_FORMAT_EAC_R11G11_UNORM_BLOCK)
    .value("EAC_R11G11_SNORM_BLOCK",                         VkFormat::VK_FORMAT_EAC_R11G11_SNORM_BLOCK)
    .value("ASTC_4x4_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_4x4_UNORM_BLOCK)
    .value("ASTC_4x4_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_4x4_SRGB_BLOCK)
    .value("ASTC_5x4_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_5x4_UNORM_BLOCK)
    .value("ASTC_5x4_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_5x4_SRGB_BLOCK)
    .value("ASTC_5x5_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_5x5_UNORM_BLOCK)
    .value("ASTC_5x5_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_5x5_SRGB_BLOCK)
    .value("ASTC_6x5_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_6x5_UNORM_BLOCK)
    .value("ASTC_6x5_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_6x5_SRGB_BLOCK)
    .value("ASTC_6x6_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_6x6_UNORM_BLOCK)
    .value("ASTC_6x6_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_6x6_SRGB_BLOCK)
    .value("ASTC_8x5_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_8x5_UNORM_BLOCK)
    .value("ASTC_8x5_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_8x5_SRGB_BLOCK)
    .value("ASTC_8x6_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_8x6_UNORM_BLOCK)
    .value("ASTC_8x6_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_8x6_SRGB_BLOCK)
    .value("ASTC_8x8_UNORM_BLOCK",                           VkFormat::VK_FORMAT_ASTC_8x8_UNORM_BLOCK)
    .value("ASTC_8x8_SRGB_BLOCK",                            VkFormat::VK_FORMAT_ASTC_8x8_SRGB_BLOCK)
    .value("ASTC_10x5_UNORM_BLOCK",                          VkFormat::VK_FORMAT_ASTC_10x5_UNORM_BLOCK)
    .value("ASTC_10x5_SRGB_BLOCK",                           VkFormat::VK_FORMAT_ASTC_10x5_SRGB_BLOCK)
    .value("ASTC_10x6_UNORM_BLOCK",                          VkFormat::VK_FORMAT_ASTC_10x6_UNORM_BLOCK)
    .value("ASTC_10x6_SRGB_BLOCK",                           VkFormat::VK_FORMAT_ASTC_10x6_SRGB_BLOCK)
    .value("ASTC_10x8_UNORM_BLOCK",                          VkFormat::VK_FORMAT_ASTC_10x8_UNORM_BLOCK)
    .value("ASTC_10x8_SRGB_BLOCK",                           VkFormat::VK_FORMAT_ASTC_10x8_SRGB_BLOCK)
    .value("ASTC_10x10_UNORM_BLOCK",                         VkFormat::VK_FORMAT_ASTC_10x10_UNORM_BLOCK)
    .value("ASTC_10x10_SRGB_BLOCK",                          VkFormat::VK_FORMAT_ASTC_10x10_SRGB_BLOCK)
    .value("ASTC_12x10_UNORM_BLOCK",                         VkFormat::VK_FORMAT_ASTC_12x10_UNORM_BLOCK)
    .value("ASTC_12x10_SRGB_BLOCK",                          VkFormat::VK_FORMAT_ASTC_12x10_SRGB_BLOCK)
    .value("ASTC_12x12_UNORM_BLOCK",                         VkFormat::VK_FORMAT_ASTC_12x12_UNORM_BLOCK)
    .value("ASTC_12x12_SRGB_BLOCK",                          VkFormat::VK_FORMAT_ASTC_12x12_SRGB_BLOCK)
    .value("G8B8G8R8_422_UNORM",                             VkFormat::VK_FORMAT_G8B8G8R8_422_UNORM)
    .value("B8G8R8G8_422_UNORM",                             VkFormat::VK_FORMAT_B8G8R8G8_422_UNORM)
    .value("G8_B8_R8_3PLANE_420_UNORM",                      VkFormat::VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM)
    .value("G8_B8R8_2PLANE_420_UNORM",                       VkFormat::VK_FORMAT_G8_B8R8_2PLANE_420_UNORM)
    .value("G8_B8_R8_3PLANE_422_UNORM",                      VkFormat::VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM)
    .value("G8_B8R8_2PLANE_422_UNORM",                       VkFormat::VK_FORMAT_G8_B8R8_2PLANE_422_UNORM)
    .value("G8_B8_R8_3PLANE_444_UNORM",                      VkFormat::VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM)
    .value("R10X6_UNORM_PACK16",                             VkFormat::VK_FORMAT_R10X6_UNORM_PACK16)
    .value("R10X6G10X6_UNORM_2PACK16",                       VkFormat::VK_FORMAT_R10X6G10X6_UNORM_2PACK16)
    .value("R10X6G10X6B10X6A10X6_UNORM_4PACK16",             VkFormat::VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16)
    .value("G10X6B10X6G10X6R10X6_422_UNORM_4PACK16",         VkFormat::VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16)
    .value("B10X6G10X6R10X6G10X6_422_UNORM_4PACK16",         VkFormat::VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16)
    .value("G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16",     VkFormat::VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16)
    .value("G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16",      VkFormat::VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16)
    .value("G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16",     VkFormat::VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16)
    .value("G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16",      VkFormat::VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16)
    .value("G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16",     VkFormat::VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16)
    .value("R12X4_UNORM_PACK16",                             VkFormat::VK_FORMAT_R12X4_UNORM_PACK16)
    .value("R12X4G12X4_UNORM_2PACK16",                       VkFormat::VK_FORMAT_R12X4G12X4_UNORM_2PACK16)
    .value("R12X4G12X4B12X4A12X4_UNORM_4PACK16",             VkFormat::VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16)
    .value("G12X4B12X4G12X4R12X4_422_UNORM_4PACK16",         VkFormat::VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16)
    .value("B12X4G12X4R12X4G12X4_422_UNORM_4PACK16",         VkFormat::VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16)
    .value("G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16",     VkFormat::VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16)
    .value("G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16",      VkFormat::VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16)
    .value("G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16",     VkFormat::VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16)
    .value("G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16",      VkFormat::VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16)
    .value("G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16",     VkFormat::VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16)
    .value("G16B16G16R16_422_UNORM",                         VkFormat::VK_FORMAT_G16B16G16R16_422_UNORM)
    .value("B16G16R16G16_422_UNORM",                         VkFormat::VK_FORMAT_B16G16R16G16_422_UNORM)
    .value("G16_B16_R16_3PLANE_420_UNORM",                   VkFormat::VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM)
    .value("G16_B16R16_2PLANE_420_UNORM",                    VkFormat::VK_FORMAT_G16_B16R16_2PLANE_420_UNORM)
    .value("G16_B16_R16_3PLANE_422_UNORM",                   VkFormat::VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM)
    .value("G16_B16R16_2PLANE_422_UNORM",                    VkFormat::VK_FORMAT_G16_B16R16_2PLANE_422_UNORM)
    .value("G16_B16_R16_3PLANE_444_UNORM",                   VkFormat::VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM)
    .value("G8_B8R8_2PLANE_444_UNORM",                       VkFormat::VK_FORMAT_G8_B8R8_2PLANE_444_UNORM)
    .value("G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16",      VkFormat::VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16)
    .value("G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16",      VkFormat::VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16)
    .value("G16_B16R16_2PLANE_444_UNORM",                    VkFormat::VK_FORMAT_G16_B16R16_2PLANE_444_UNORM)
    .value("A4R4G4B4_UNORM_PACK16",                          VkFormat::VK_FORMAT_A4R4G4B4_UNORM_PACK16)
    .value("A4B4G4R4_UNORM_PACK16",                          VkFormat::VK_FORMAT_A4B4G4R4_UNORM_PACK16)
    .value("ASTC_4x4_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK)
    .value("ASTC_5x4_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK)
    .value("ASTC_5x5_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK)
    .value("ASTC_6x5_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK)
    .value("ASTC_6x6_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK)
    .value("ASTC_8x5_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK)
    .value("ASTC_8x6_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK)
    .value("ASTC_8x8_SFLOAT_BLOCK",                          VkFormat::VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK)
    .value("ASTC_10x5_SFLOAT_BLOCK",                         VkFormat::VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK)
    .value("ASTC_10x6_SFLOAT_BLOCK",                         VkFormat::VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK)
    .value("ASTC_10x8_SFLOAT_BLOCK",                         VkFormat::VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK)
    .value("ASTC_10x10_SFLOAT_BLOCK",                        VkFormat::VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK)
    .value("ASTC_12x10_SFLOAT_BLOCK",                        VkFormat::VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK)
    .value("ASTC_12x12_SFLOAT_BLOCK",                        VkFormat::VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK)
    .value("A1B5G5R5_UNORM_PACK16",                          VkFormat::VK_FORMAT_A1B5G5R5_UNORM_PACK16)
    .value("A8_UNORM",                                       VkFormat::VK_FORMAT_A8_UNORM)
    .value("PVRTC1_2BPP_UNORM_BLOCK_IMG",                    VkFormat::VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG)
    .value("PVRTC1_4BPP_UNORM_BLOCK_IMG",                    VkFormat::VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG)
    .value("PVRTC2_2BPP_UNORM_BLOCK_IMG",                    VkFormat::VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG)
    .value("PVRTC2_4BPP_UNORM_BLOCK_IMG",                    VkFormat::VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG)
    .value("PVRTC1_2BPP_SRGB_BLOCK_IMG",                     VkFormat::VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG)
    .value("PVRTC1_4BPP_SRGB_BLOCK_IMG",                     VkFormat::VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG)
    .value("PVRTC2_2BPP_SRGB_BLOCK_IMG",                     VkFormat::VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG)
    .value("PVRTC2_4BPP_SRGB_BLOCK_IMG",                     VkFormat::VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG)
    .value("R16G16_SFIXED5_NV",                              VkFormat::VK_FORMAT_R16G16_SFIXED5_NV)
    .value("ASTC_4x4_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT)
    .value("ASTC_5x4_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT)
    .value("ASTC_5x5_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT)
    .value("ASTC_6x5_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT)
    .value("ASTC_6x6_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT)
    .value("ASTC_8x5_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT)
    .value("ASTC_8x6_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT)
    .value("ASTC_8x8_SFLOAT_BLOCK_EXT",                      VkFormat::VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT)
    .value("ASTC_10x5_SFLOAT_BLOCK_EXT",                     VkFormat::VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT)
    .value("ASTC_10x6_SFLOAT_BLOCK_EXT",                     VkFormat::VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT)
    .value("ASTC_10x8_SFLOAT_BLOCK_EXT",                     VkFormat::VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT)
    .value("ASTC_10x10_SFLOAT_BLOCK_EXT",                    VkFormat::VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT)
    .value("ASTC_12x10_SFLOAT_BLOCK_EXT",                    VkFormat::VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT)
    .value("ASTC_12x12_SFLOAT_BLOCK_EXT",                    VkFormat::VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT)
    .value("G8B8G8R8_422_UNORM_KHR",                         VkFormat::VK_FORMAT_G8B8G8R8_422_UNORM_KHR)
    .value("B8G8R8G8_422_UNORM_KHR",                         VkFormat::VK_FORMAT_B8G8R8G8_422_UNORM_KHR)
    .value("G8_B8_R8_3PLANE_420_UNORM_KHR",                  VkFormat::VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR)
    .value("G8_B8R8_2PLANE_420_UNORM_KHR",                   VkFormat::VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR)
    .value("G8_B8_R8_3PLANE_422_UNORM_KHR",                  VkFormat::VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR)
    .value("G8_B8R8_2PLANE_422_UNORM_KHR",                   VkFormat::VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR)
    .value("G8_B8_R8_3PLANE_444_UNORM_KHR",                  VkFormat::VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR)
    .value("R10X6_UNORM_PACK16_KHR",                         VkFormat::VK_FORMAT_R10X6_UNORM_PACK16_KHR)
    .value("R10X6G10X6_UNORM_2PACK16_KHR",                   VkFormat::VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR)
    .value("R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR",         VkFormat::VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR)
    .value("G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR",     VkFormat::VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR)
    .value("B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR",     VkFormat::VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR)
    .value("G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR", VkFormat::VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR)
    .value("G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR",  VkFormat::VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR)
    .value("G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR", VkFormat::VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR)
    .value("G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR",  VkFormat::VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR)
    .value("G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR", VkFormat::VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR)
    .value("R12X4_UNORM_PACK16_KHR",                         VkFormat::VK_FORMAT_R12X4_UNORM_PACK16_KHR)
    .value("R12X4G12X4_UNORM_2PACK16_KHR",                   VkFormat::VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR)
    .value("R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR",         VkFormat::VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR)
    .value("G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR",     VkFormat::VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR)
    .value("B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR",     VkFormat::VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR)
    .value("G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR", VkFormat::VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR)
    .value("G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR",  VkFormat::VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR)
    .value("G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR", VkFormat::VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR)
    .value("G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR",  VkFormat::VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR)
    .value("G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR", VkFormat::VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR)
    .value("G16B16G16R16_422_UNORM_KHR",                     VkFormat::VK_FORMAT_G16B16G16R16_422_UNORM_KHR)
    .value("B16G16R16G16_422_UNORM_KHR",                     VkFormat::VK_FORMAT_B16G16R16G16_422_UNORM_KHR)
    .value("G16_B16_R16_3PLANE_420_UNORM_KHR",               VkFormat::VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR)
    .value("G16_B16R16_2PLANE_420_UNORM_KHR",                VkFormat::VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR)
    .value("G16_B16_R16_3PLANE_422_UNORM_KHR",               VkFormat::VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR)
    .value("G16_B16R16_2PLANE_422_UNORM_KHR",                VkFormat::VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR)
    .value("G16_B16_R16_3PLANE_444_UNORM_KHR",               VkFormat::VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR)
    .value("G8_B8R8_2PLANE_444_UNORM_EXT",                   VkFormat::VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT)
    .value("G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT",  VkFormat::VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT)
    .value("G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT",  VkFormat::VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT)
    .value("G16_B16R16_2PLANE_444_UNORM_EXT",                VkFormat::VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT)
    .value("A4R4G4B4_UNORM_PACK16_EXT",                      VkFormat::VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT)
    .value("A4B4G4R4_UNORM_PACK16_EXT",                      VkFormat::VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT)
    .value("R16G16_S10_5_NV",                                VkFormat::VK_FORMAT_R16G16_S10_5_NV)
    .value("A1B5G5R5_UNORM_PACK16_KHR",                      VkFormat::VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR)
    .value("A8_UNORM_KHR",                                   VkFormat::VK_FORMAT_A8_UNORM_KHR)
    .value("MAX_ENUM",                                       VkFormat::VK_FORMAT_MAX_ENUM)
    .export_values();

py::enum_<VkImageLayout>(m, "VkImageLayout", py::arithmetic())
    .value("UNDEFINED",                                      VkImageLayout::VK_IMAGE_LAYOUT_UNDEFINED)
    .value("GENERAL",                                        VkImageLayout::VK_IMAGE_LAYOUT_GENERAL)
    .value("COLOR_ATTACHMENT_OPTIMAL",                       VkImageLayout::VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL)
    .value("DEPTH_STENCIL_ATTACHMENT_OPTIMAL",               VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL)
    .value("DEPTH_STENCIL_READ_ONLY_OPTIMAL",                VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL)
    .value("SHADER_READ_ONLY_OPTIMAL",                       VkImageLayout::VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL)
    .value("TRANSFER_SRC_OPTIMAL",                           VkImageLayout::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL)
    .value("TRANSFER_DST_OPTIMAL",                           VkImageLayout::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL)
    .value("PREINITIALIZED",                                 VkImageLayout::VK_IMAGE_LAYOUT_PREINITIALIZED)
    .value("DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL",     VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL)
    .value("DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL",     VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL)
    .value("DEPTH_ATTACHMENT_OPTIMAL",                       VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL)
    .value("DEPTH_READ_ONLY_OPTIMAL",                        VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL)
    .value("STENCIL_ATTACHMENT_OPTIMAL",                     VkImageLayout::VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL)
    .value("STENCIL_READ_ONLY_OPTIMAL",                      VkImageLayout::VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL)
    .value("READ_ONLY_OPTIMAL",                              VkImageLayout::VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL)
    .value("ATTACHMENT_OPTIMAL",                             VkImageLayout::VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL)
    .value("RENDERING_LOCAL_READ",                           VkImageLayout::VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ)
    .value("PRESENT_SRC_KHR",                                VkImageLayout::VK_IMAGE_LAYOUT_PRESENT_SRC_KHR)
    .value("VIDEO_DECODE_DST_KHR",                           VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR)
    .value("VIDEO_DECODE_SRC_KHR",                           VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR)
    .value("VIDEO_DECODE_DPB_KHR",                           VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR)
    .value("SHARED_PRESENT_KHR",                             VkImageLayout::VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR)
    .value("FRAGMENT_DENSITY_MAP_OPTIMAL_EXT",               VkImageLayout::VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT)
    .value("FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR",   VkImageLayout::VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR)
    .value("VIDEO_ENCODE_DST_KHR",                           VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR)
    .value("VIDEO_ENCODE_SRC_KHR",                           VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR)
    .value("VIDEO_ENCODE_DPB_KHR",                           VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR)
    .value("ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT",           VkImageLayout::VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT)
    .value("VIDEO_ENCODE_QUANTIZATION_MAP_KHR",              VkImageLayout::VK_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR)
    .value("DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR", VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR)
    .value("DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR", VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR)
    .value("SHADING_RATE_OPTIMAL_NV",                        VkImageLayout::VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV)
    .value("RENDERING_LOCAL_READ_KHR",                       VkImageLayout::VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR)
    .value("DEPTH_ATTACHMENT_OPTIMAL_KHR",                   VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR)
    .value("DEPTH_READ_ONLY_OPTIMAL_KHR",                    VkImageLayout::VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR)
    .value("STENCIL_ATTACHMENT_OPTIMAL_KHR",                 VkImageLayout::VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR)
    .value("STENCIL_READ_ONLY_OPTIMAL_KHR",                  VkImageLayout::VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR)
    .value("READ_ONLY_OPTIMAL_KHR",                          VkImageLayout::VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR)
    .value("ATTACHMENT_OPTIMAL_KHR",                         VkImageLayout::VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR)
    .value("MAX_ENUM",                                       VkImageLayout::VK_IMAGE_LAYOUT_MAX_ENUM)
    .export_values();

py::class_<skgpu::VulkanAlloc>(m, "GrVkAlloc")
    .def(py::init<>())
    // TODO: Implement me!
    ;

py::class_<skgpu::VulkanYcbcrConversionInfo>(m, "GrVkYcbcrConversionInfo")
    .def(py::init<>())
    // TODO: Implement me!
    ;

py::class_<GrVkImageInfo>(m, "GrVkImageInfo",
    R"docstring(
    When wrapping a GrBackendTexture or GrBackendRendenderTarget, the
    fCurrentQueueFamily should either be VK_QUEUE_FAMILY_IGNORED,
    VK_QUEUE_FAMILY_EXTERNAL, or VK_QUEUE_FAMILY_FOREIGN_EXT. If fSharingMode is
    VK_SHARING_MODE_EXCLUSIVE then fCurrentQueueFamily can also be the graphics
    queue index passed into Skia.
    )docstring")
    .def(py::init<>())
    // .def(py::init(
    //     [] (VkImage image,
    //         skgpu::VulkanAlloc alloc,
    //         VkImageTiling imageTiling,
    //         VkImageLayout layout,
    //         VkFormat format,
    //         uint32_t levelCount,
    //         uint32_t currentQueueFamily,
    //         GrProtected isProtected,
    //         const skgpu::VulkanYcbcrConversionInfo* ycbcrConversionInfo) {
    //         return GrVkImageInfo(
    //             image, alloc, imageTiling, layout, format, levelCount,
    //             currentQueueFamily, isProtected,
    //             (ycbcrConversionInfo) ?
    //                 *ycbcrConversionInfo : skgpu::VulkanYcbcrConversionInfo());
    //     }),
    //     py::arg("image"), py::arg("alloc"), py::arg("imageTiling"),
    //     py::arg("layout"), py::arg("format"), py::arg("levelCount"),
    //     py::arg("currentQueueFamily") = VK_QUEUE_FAMILY_IGNORED,
    //     py::arg("isProtected") = GrProtected::kNo,
    //     py::arg("ycbcrConversionInfo") = nullptr)
    // .def_readwrite("fImage", &GrVkImageInfo::fImage)
    .def_readwrite("fAlloc", &GrVkImageInfo::fAlloc)
    // .def_readwrite("fImageTiling", &GrVkImageInfo::fImageTiling)
    // .def_readwrite("fImageLayout", &GrVkImageInfo::fImageLayout)
    // .def_readwrite("fFormat", &GrVkImageInfo::fFormat)
    .def_readwrite("fLevelCount", &GrVkImageInfo::fLevelCount)
    .def_readwrite("fCurrentQueueFamily", &GrVkImageInfo::fCurrentQueueFamily)
    .def_readwrite("fProtected", &GrVkImageInfo::fProtected)
    .def_readwrite("fYcbcrConversionInfo", &GrVkImageInfo::fYcbcrConversionInfo)
    .def_readwrite("fSharingMode", &GrVkImageInfo::fSharingMode)
    ;

py::class_<GrVkDrawableInfo>(m, "GrVkDrawableInfo")
    // TODO: Implement me!
    ;

// GrVkBackendContext.h
/* GrVkExtensionFlags & GrVkFeatureFlags removed in m127 */
/*
py::enum_<GrVkExtensionFlags>(m, "GrVkExtensionFlags", py::arithmetic())
    .value("kEXT_debug_report_GrVkExtensionFlag",
        GrVkExtensionFlags::kEXT_debug_report_GrVkExtensionFlag)
    .value("kNV_glsl_shader_GrVkExtensionFlag",
        GrVkExtensionFlags::kNV_glsl_shader_GrVkExtensionFlag)
    .value("kKHR_surface_GrVkExtensionFlag",
        GrVkExtensionFlags::kKHR_surface_GrVkExtensionFlag)
    .value("kKHR_swapchain_GrVkExtensionFlag",
        GrVkExtensionFlags::kKHR_swapchain_GrVkExtensionFlag)
    .value("kKHR_win32_surface_GrVkExtensionFlag",
        GrVkExtensionFlags::kKHR_win32_surface_GrVkExtensionFlag)
    .value("kKHR_android_surface_GrVkExtensionFlag",
        GrVkExtensionFlags::kKHR_android_surface_GrVkExtensionFlag)
    .value("kKHR_xcb_surface_GrVkExtensionFlag",
        GrVkExtensionFlags::kKHR_xcb_surface_GrVkExtensionFlag)
    .export_values();

py::enum_<GrVkFeatureFlags>(m, "GrVkFeatureFlags", py::arithmetic())
    .value("kGeometryShader_GrVkFeatureFlag",
        GrVkFeatureFlags::kGeometryShader_GrVkFeatureFlag)
    .value("kDualSrcBlend_GrVkFeatureFlag",
        GrVkFeatureFlags::kDualSrcBlend_GrVkFeatureFlag)
    .value("kSampleRateShading_GrVkFeatureFlag",
        GrVkFeatureFlags::kSampleRateShading_GrVkFeatureFlag)
    .export_values();
*/

py::class_<skgpu::VulkanBackendContext>(m, "GrVkBackendContext",
    R"docstring(
    The BackendContext contains all of the base Vulkan objects needed by the
    GrVkGpu. The assumption is that the client will set these up and pass them
    to the GrVkGpu constructor. The VkDevice created must support at least one
    graphics queue, which is passed in as well. The QueueFamilyIndex must match
    the family of the given queue. It is needed for CommandPool creation, and
    any GrBackendObjects handed to us (e.g., for wrapped textures) needs to be
    created in or transitioned to that family. The refs held by members of this
    struct must be released (either by deleting the struct or manually releasing
    the refs) before the underlying vulkan device and instance are destroyed.
    )docstring")
    .def(py::init<>())
    // TODO: Implement me!
    ;

py::object SimpleNamespace = py::module_::import("types").attr("SimpleNamespace");
m.attr("skgpu") = SimpleNamespace();
m.attr("skgpu").attr("VulkanBackendContext") = m.attr("GrVkBackendContext");
m.attr("skgpu").attr("VulkanAlloc") = m.attr("GrVkAlloc");
m.attr("skgpu").attr("VulkanYcbcrConversionInfo") = m.attr("GrVkYcbcrConversionInfo");
}
